version: '3'

services:
  builder:
    build: ./builder
    volumes:
      - ./app:/app
    command: mvn clean package
  prod:
    build: ./prod
    ports:
      - "8080:8080"
    depends_on:
      - builder
