version: '3.7'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile-builder
    volumes:
      - .:/app
    working_dir: /app
    command: ant build
  prod:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8080:8080"
    depends_on:
      - builder

