version: "3.7"

services:
  builder:
    build: ./builder
  prod:
    build: ./Prod
    volumes:
      - ./build/boxfuse-sample-java-war-hello/target/hello-1.0.war
    ports:
      - "8080:8080"
    depends_on:
      - builder
